export const Fonts = {
  Balo: 'BalooBhaina-Regular',
  Kati: 'Katibeh-Regular',
  Pacifico: 'Pacifico-Regular',
  Lobster: 'Lobster-Regular',
  Caveat: 'CaveatBrush-Regular',
  Chewy: 'Chewy-Regular',
  montserratBlackItalic: 'Montserrat-BlackItalic',
  montserratMediumItalic: 'Montserrat-MediumItalic',
  montserratBold: 'Montserrat-SemiBoldItalic',
  Indie: 'IndieFlower-Regular',
  Fredo: 'FredokaOne-Regular',
  Modak: 'Modak-Regular',
  RobotoBoldItal: 'RobotoCondensed-BoldItalic',
  RobotoBold: 'RobotoCondensed-Bold',
  LatoBlack: 'Lato-Black',
  LatoBlackItal: 'Lato-BlackItalic',
  JosefItal: 'JosefinSans-Italic-VariableFont_wght',
  JosefNormal: 'JosefinSans-VariableFont_wght',
  AmiriBold: 'Amiri-Bold',
  AmiriBoldItal: 'Amiri-BoldItalic',
};
